services:
    postgres:
        image: postgres:17.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DATABASE=postgres
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data 
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U docker"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7.4-alpine
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        environment:
            - REDIS_PASSWORD=docker
        command: redis-server --requirepass docker
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "your_secure_password", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes: 
    db:
    redis:
