services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DATABASE=postgres
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgres 
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U docker"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes: 
    db:
